/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaticAppShellRouteImport } from './routes/static-app-shell'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MenubarRouteImport } from './routes/menubar'
import { Route as MembersRouteImport } from './routes/members'
import { Route as InstallShRouteImport } from './routes/install-sh'
import { Route as InstallRouteImport } from './routes/install'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsPoliciesRouteImport } from './routes/tools/policies'
import { Route as ToolsEditorRouteImport } from './routes/tools/editor'
import { Route as ToolsConnectionsRouteImport } from './routes/tools/connections'
import { Route as ToolsCatalogRouteImport } from './routes/tools/catalog'
import { Route as McpOauthStartRouteImport } from './routes/mcp/oauth/start'
import { Route as McpOauthResultRouteImport } from './routes/mcp/oauth/result'
import { Route as McpOauthDetectRouteImport } from './routes/mcp/oauth/detect'
import { Route as McpOauthCompleteRouteImport } from './routes/mcp/oauth/complete'
import { Route as McpOauthCallbackRouteImport } from './routes/mcp/oauth/callback'
import { Route as ApiOpenapiInspectRouteImport } from './routes/api/openapi/inspect'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthAnonymousTokenRouteImport } from './routes/api/auth/anonymous-token'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticAppShellRoute = StaticAppShellRouteImport.update({
  id: '/static-app-shell',
  path: '/static-app-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MenubarRoute = MenubarRouteImport.update({
  id: '/menubar',
  path: '/menubar',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallShRoute = InstallShRouteImport.update({
  id: '/install-sh',
  path: '/install-sh',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPoliciesRoute = ToolsPoliciesRouteImport.update({
  id: '/tools/policies',
  path: '/tools/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEditorRoute = ToolsEditorRouteImport.update({
  id: '/tools/editor',
  path: '/tools/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsConnectionsRoute = ToolsConnectionsRouteImport.update({
  id: '/tools/connections',
  path: '/tools/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCatalogRoute = ToolsCatalogRouteImport.update({
  id: '/tools/catalog',
  path: '/tools/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const McpOauthStartRoute = McpOauthStartRouteImport.update({
  id: '/mcp/oauth/start',
  path: '/mcp/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const McpOauthResultRoute = McpOauthResultRouteImport.update({
  id: '/mcp/oauth/result',
  path: '/mcp/oauth/result',
  getParentRoute: () => rootRouteImport,
} as any)
const McpOauthDetectRoute = McpOauthDetectRouteImport.update({
  id: '/mcp/oauth/detect',
  path: '/mcp/oauth/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const McpOauthCompleteRoute = McpOauthCompleteRouteImport.update({
  id: '/mcp/oauth/complete',
  path: '/mcp/oauth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const McpOauthCallbackRoute = McpOauthCallbackRouteImport.update({
  id: '/mcp/oauth/callback',
  path: '/mcp/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiInspectRoute = ApiOpenapiInspectRouteImport.update({
  id: '/api/openapi/inspect',
  path: '/api/openapi/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAnonymousTokenRoute = ApiAuthAnonymousTokenRouteImport.update({
  id: '/api/auth/anonymous-token',
  path: '/api/auth/anonymous-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/install': typeof InstallRoute
  '/install-sh': typeof InstallShRoute
  '/members': typeof MembersRoute
  '/menubar': typeof MenubarRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/static-app-shell': typeof StaticAppShellRoute
  '/tasks': typeof TasksRoute
  '/tools/catalog': typeof ToolsCatalogRoute
  '/tools/connections': typeof ToolsConnectionsRoute
  '/tools/editor': typeof ToolsEditorRoute
  '/tools/policies': typeof ToolsPoliciesRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/anonymous-token': typeof ApiAuthAnonymousTokenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/openapi/inspect': typeof ApiOpenapiInspectRoute
  '/mcp/oauth/callback': typeof McpOauthCallbackRoute
  '/mcp/oauth/complete': typeof McpOauthCompleteRoute
  '/mcp/oauth/detect': typeof McpOauthDetectRoute
  '/mcp/oauth/result': typeof McpOauthResultRoute
  '/mcp/oauth/start': typeof McpOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/install': typeof InstallRoute
  '/install-sh': typeof InstallShRoute
  '/members': typeof MembersRoute
  '/menubar': typeof MenubarRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/static-app-shell': typeof StaticAppShellRoute
  '/tasks': typeof TasksRoute
  '/tools/catalog': typeof ToolsCatalogRoute
  '/tools/connections': typeof ToolsConnectionsRoute
  '/tools/editor': typeof ToolsEditorRoute
  '/tools/policies': typeof ToolsPoliciesRoute
  '/tools': typeof ToolsIndexRoute
  '/api/auth/anonymous-token': typeof ApiAuthAnonymousTokenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/openapi/inspect': typeof ApiOpenapiInspectRoute
  '/mcp/oauth/callback': typeof McpOauthCallbackRoute
  '/mcp/oauth/complete': typeof McpOauthCompleteRoute
  '/mcp/oauth/detect': typeof McpOauthDetectRoute
  '/mcp/oauth/result': typeof McpOauthResultRoute
  '/mcp/oauth/start': typeof McpOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/install': typeof InstallRoute
  '/install-sh': typeof InstallShRoute
  '/members': typeof MembersRoute
  '/menubar': typeof MenubarRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/static-app-shell': typeof StaticAppShellRoute
  '/tasks': typeof TasksRoute
  '/tools/catalog': typeof ToolsCatalogRoute
  '/tools/connections': typeof ToolsConnectionsRoute
  '/tools/editor': typeof ToolsEditorRoute
  '/tools/policies': typeof ToolsPoliciesRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/anonymous-token': typeof ApiAuthAnonymousTokenRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/openapi/inspect': typeof ApiOpenapiInspectRoute
  '/mcp/oauth/callback': typeof McpOauthCallbackRoute
  '/mcp/oauth/complete': typeof McpOauthCompleteRoute
  '/mcp/oauth/detect': typeof McpOauthDetectRoute
  '/mcp/oauth/result': typeof McpOauthResultRoute
  '/mcp/oauth/start': typeof McpOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/billing'
    | '/callback'
    | '/install'
    | '/install-sh'
    | '/members'
    | '/menubar'
    | '/onboarding'
    | '/organization'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/static-app-shell'
    | '/tasks'
    | '/tools/catalog'
    | '/tools/connections'
    | '/tools/editor'
    | '/tools/policies'
    | '/tools/'
    | '/api/auth/anonymous-token'
    | '/api/auth/callback'
    | '/api/openapi/inspect'
    | '/mcp/oauth/callback'
    | '/mcp/oauth/complete'
    | '/mcp/oauth/detect'
    | '/mcp/oauth/result'
    | '/mcp/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/billing'
    | '/callback'
    | '/install'
    | '/install-sh'
    | '/members'
    | '/menubar'
    | '/onboarding'
    | '/organization'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/static-app-shell'
    | '/tasks'
    | '/tools/catalog'
    | '/tools/connections'
    | '/tools/editor'
    | '/tools/policies'
    | '/tools'
    | '/api/auth/anonymous-token'
    | '/api/auth/callback'
    | '/api/openapi/inspect'
    | '/mcp/oauth/callback'
    | '/mcp/oauth/complete'
    | '/mcp/oauth/detect'
    | '/mcp/oauth/result'
    | '/mcp/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/billing'
    | '/callback'
    | '/install'
    | '/install-sh'
    | '/members'
    | '/menubar'
    | '/onboarding'
    | '/organization'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/static-app-shell'
    | '/tasks'
    | '/tools/catalog'
    | '/tools/connections'
    | '/tools/editor'
    | '/tools/policies'
    | '/tools/'
    | '/api/auth/anonymous-token'
    | '/api/auth/callback'
    | '/api/openapi/inspect'
    | '/mcp/oauth/callback'
    | '/mcp/oauth/complete'
    | '/mcp/oauth/detect'
    | '/mcp/oauth/result'
    | '/mcp/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BillingRoute: typeof BillingRoute
  CallbackRoute: typeof CallbackRoute
  InstallRoute: typeof InstallRoute
  InstallShRoute: typeof InstallShRoute
  MembersRoute: typeof MembersRoute
  MenubarRoute: typeof MenubarRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationRoute: typeof OrganizationRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  SignUpRoute: typeof SignUpRoute
  StaticAppShellRoute: typeof StaticAppShellRoute
  TasksRoute: typeof TasksRoute
  ToolsCatalogRoute: typeof ToolsCatalogRoute
  ToolsConnectionsRoute: typeof ToolsConnectionsRoute
  ToolsEditorRoute: typeof ToolsEditorRoute
  ToolsPoliciesRoute: typeof ToolsPoliciesRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAuthAnonymousTokenRoute: typeof ApiAuthAnonymousTokenRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiOpenapiInspectRoute: typeof ApiOpenapiInspectRoute
  McpOauthCallbackRoute: typeof McpOauthCallbackRoute
  McpOauthCompleteRoute: typeof McpOauthCompleteRoute
  McpOauthDetectRoute: typeof McpOauthDetectRoute
  McpOauthResultRoute: typeof McpOauthResultRoute
  McpOauthStartRoute: typeof McpOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/static-app-shell': {
      id: '/static-app-shell'
      path: '/static-app-shell'
      fullPath: '/static-app-shell'
      preLoaderRoute: typeof StaticAppShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menubar': {
      id: '/menubar'
      path: '/menubar'
      fullPath: '/menubar'
      preLoaderRoute: typeof MenubarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-sh': {
      id: '/install-sh'
      path: '/install-sh'
      fullPath: '/install-sh'
      preLoaderRoute: typeof InstallShRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/policies': {
      id: '/tools/policies'
      path: '/tools/policies'
      fullPath: '/tools/policies'
      preLoaderRoute: typeof ToolsPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/editor': {
      id: '/tools/editor'
      path: '/tools/editor'
      fullPath: '/tools/editor'
      preLoaderRoute: typeof ToolsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/connections': {
      id: '/tools/connections'
      path: '/tools/connections'
      fullPath: '/tools/connections'
      preLoaderRoute: typeof ToolsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/catalog': {
      id: '/tools/catalog'
      path: '/tools/catalog'
      fullPath: '/tools/catalog'
      preLoaderRoute: typeof ToolsCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/oauth/start': {
      id: '/mcp/oauth/start'
      path: '/mcp/oauth/start'
      fullPath: '/mcp/oauth/start'
      preLoaderRoute: typeof McpOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/oauth/result': {
      id: '/mcp/oauth/result'
      path: '/mcp/oauth/result'
      fullPath: '/mcp/oauth/result'
      preLoaderRoute: typeof McpOauthResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/oauth/detect': {
      id: '/mcp/oauth/detect'
      path: '/mcp/oauth/detect'
      fullPath: '/mcp/oauth/detect'
      preLoaderRoute: typeof McpOauthDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/oauth/complete': {
      id: '/mcp/oauth/complete'
      path: '/mcp/oauth/complete'
      fullPath: '/mcp/oauth/complete'
      preLoaderRoute: typeof McpOauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/oauth/callback': {
      id: '/mcp/oauth/callback'
      path: '/mcp/oauth/callback'
      fullPath: '/mcp/oauth/callback'
      preLoaderRoute: typeof McpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/inspect': {
      id: '/api/openapi/inspect'
      path: '/api/openapi/inspect'
      fullPath: '/api/openapi/inspect'
      preLoaderRoute: typeof ApiOpenapiInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/anonymous-token': {
      id: '/api/auth/anonymous-token'
      path: '/api/auth/anonymous-token'
      fullPath: '/api/auth/anonymous-token'
      preLoaderRoute: typeof ApiAuthAnonymousTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BillingRoute: BillingRoute,
  CallbackRoute: CallbackRoute,
  InstallRoute: InstallRoute,
  InstallShRoute: InstallShRoute,
  MembersRoute: MembersRoute,
  MenubarRoute: MenubarRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationRoute: OrganizationRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  SignUpRoute: SignUpRoute,
  StaticAppShellRoute: StaticAppShellRoute,
  TasksRoute: TasksRoute,
  ToolsCatalogRoute: ToolsCatalogRoute,
  ToolsConnectionsRoute: ToolsConnectionsRoute,
  ToolsEditorRoute: ToolsEditorRoute,
  ToolsPoliciesRoute: ToolsPoliciesRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAuthAnonymousTokenRoute: ApiAuthAnonymousTokenRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiOpenapiInspectRoute: ApiOpenapiInspectRoute,
  McpOauthCallbackRoute: McpOauthCallbackRoute,
  McpOauthCompleteRoute: McpOauthCompleteRoute,
  McpOauthDetectRoute: McpOauthDetectRoute,
  McpOauthResultRoute: McpOauthResultRoute,
  McpOauthStartRoute: McpOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
